### ISSUE TITLE
Resource with @Path("/") is ignored

### ISSUE THREAD

**Issue by loucasa** [teamcarma/swagger-jaxrs-doclet#44]
Not sure if I am missing something but if I change the value so that it is not root then it works

**Comment by alexradzin** [comment]
I experienced the same issue and worked it around by changing values of @Path annotation. I was lucky that I could do this in my case.

**Comment by conorroche** [comment]
I have now fixed this so that by default resources with path of @Path("/") or @Path("") will have a resource root path of /root but this can be customized either by using the doclet param -resourceRootPath or by using the @resourcePath javadoc tag on the class, 

NOTE for people with version prior to this fix you can have solve it by setting the resourcePath javadoc tag on the class e.g. 

/**
 * @resourcePath /customroot
 */
@Path("/")
@SuppressWarnings("javadoc")
public class RootPathResource {

	@GET
	@Path("/v1/message")
	public String getMessage() {
		return "success";
	}

}

**Comment by conorroche** [comment]
@loucasa or @alexradzin  can you let me know if this has solved your issues now?

**Comment by loucasa** [comment]
The latest works for me now thanks but note the @resourcePath workaround does not work on v1.0.3 or below, seems the checkin "fix for issue 46" allowed the workaround to work
